### ISSUE TITLE
Add district offices for 115th Congress

### ISSUE THREAD

**Issue by tcarobruce** [TheWalkers/congress-legislators#1]
legislators-current.yaml has been updated, most members have URLs, should be able to load district offices.

**Comment by tcarobruce** [comment]
Commit 7a611f8 adds district offices for members with working URLs as of 2017-12-11.

Some members still do not have URLs, or have not set up district offices.
New Senate Members:
* D000622,Tammy Duckworth
* C001113,Catherine Cortez Masto
* H001075,Kamala Harris
* H001076,Maggie Hassan
* K000393,John Neely Kennedy
* V000128,Chris Van Hollen
* Y000064,Todd Young

House Members without district offices:
* B001301,https://bergman.house.gov,Rep. Jack Bergman,MI
* C001110,https://correa.house.gov,Rep. J. Correa,CA
* E000297,https://espaillat.house.gov,Rep. Adriano Espaillat,NY
* H001077,https://clayhiggins.house.gov,Rep. Clay Higgins,LA
* T000477,https://taylor.house.gov,Rep. Scott Taylor,VA

**Comment by jlgoldman** [comment]
I have a branch ready that has geocodes for all offices, a geocoding script, and address corrections, but I don't have permission to push to the remote. Could you grant me permission and then I'll send a pull request? Thanks!

**Comment by TheWalkers** [comment]
Hey there!

That's awesome, thank you.  I can't give you push rights because we feed production systems from this fork, so need the ability to review, but you shouldn't need them to submit a pull request.  We merged a pull request from another github user who didn't have any special rights last week.  I think all you'll need to do is create your own fork on Github and then submit the pull request from that fork.

Let me know if I'm missing something!

**Comment by jlgoldman** [comment]
Ok will do a fork-based pull request instead of a branched-based one. Incoming.

**Comment by UnicycleJonathan** [comment]
Thanks for integrating the geocodes!

In the course of doing them I discovered a few too many cases where the addresses are wrong, typically with street names omitted. So I'm a little worried about the data quality, because I was only able to catch cases where geocoding was obviously wrong and not cases where Google Maps did a best-guess and gave a result that could be miles away but still in the same town.

For example, Rep. James Risch (bioguide R000584) had an office listed as "1411 East" when the real address is "1411 Falls Avenue East". And Rep. Christopher Smith (bioguide S000522) had an address as "539 Road)" which should have been "405 Route 539". This scares me as to the reliability of the Mechanical Turk workers to do things correctly. Or perhaps there was a bug in an address parser/validator that threw out address elements erroneously?

I've written a quick script that looks for the distance of each office in the dataset to a corresponding office in my dataset at https://github.com/jlgoldman/membersofcongress, and found another 60 offices that seem to be miles from their correct locations. I will go try to fix these this week, but I'm wondering if either (1) there should be another Mechanical Turk job to provide an office address and the website and have a worker validate that it is indeed correct, or (2) pull the data from my dataset instead. I pulled them all myself with the help of a parers and at this point trust my ability not to make mistakes a little more than the Turkers.

What do you guys think?

**Comment by UnicycleJonathan** [comment]
(And oops, meant to make these comments from my other Github account, sorry for the confusion.)

**Comment by tcarobruce** [comment]
Commit 8bf5d13 adds offices for more members, leaving just a few holdouts:

```
Senate:
K000393,https://www.kennedy.senate.gov/,John Neely Kennedy,LA
V000128,https://www.vanhollen.senate.gov,Chris Van Hollen,MD

House:
C001110,https://correa.house.gov,Rep. J. Correa,CA
H001077,https://clayhiggins.house.gov,Rep. Clay Higgins,LA
T000477,https://taylor.house.gov,Rep. Scott Taylor,VA
```

**Comment by tcarobruce** [comment]
7912a34 closes this issue, with offices for all (initial) members of the 115th Congress.
